language: csharp
mono: none
dotnet: 2.1.502
solution: Cactus.Blade.Immuable.sln
install:
  - dotnet restore
script:
  - dotnet msbuild /p:Configuration=Release Cactus.Blade.Immuable.sln
  - dotnet restore
  - dotnet test Immuable.Test/Immuable.Test.csproj
